site_name: Notas Musicais #Configura o nome do projeto
repo_url: https://github.com/Ro-Goncalves/notas-musicais # Link do repositório
repo_name: ro-goncalves/notas-musicais # Nome do repositório
edit_uri: tree/master/docs # Caminho da documentação

theme:  
  name: material # Configura o nome do tema  
  language: pt-BR # Configura o idioma
  logo: assets/logo.png # Configura o logo
  favicon: assets/logo.png # Configura o favicon

markdown_extensions:
  - attr_list # Permite colocar atributos no markdown, exemplo ![logo-projeto](assets/logo.png){width="300"}
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css # Inclui um CSS no doc

watch:
  - notas_musicais # Toda vez que atualizar o arquivo, sobe a atualização

plugins:
- macros  
-  mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais]

extra: # Configura as variáveis que serão usadas nas macros
  commands:
    run: poetry run notas-musicais
