name: Pipelene
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copia os arquivos ro repo
        uses: actions/checkout@v3.3.0

      - name: Roda um comando
        run: echo $(ls)